# Generated by Django 3.1.5 on 2021-02-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('balance', models.IntegerField(default='100')),
            ],
        ),
        migrations.CreateModel(
            name='transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromName', models.CharField(default='null', max_length=200)),
                ('toName', models.CharField(default='null', max_length=200)),
                ('amount', models.IntegerField()),
                ('fromC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromc', to='main.customer')),
                ('toC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
    ]
